version: '2.1'
services:
  java-oracle-9-jdk-alpine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - IMAGE_ARG_ALPINE_MIRROR=${IMAGE_ARG_ALPINE_MIRROR:-mirror.tuna.tsinghua.edu.cn}
      - IMAGE_ARG_ENCODING=${IMAGE_ARG_ENCODING:-UTF-8}
      - IMAGE_ARG_LOCALE=${IMAGE_ARG_LOCALE:-en_US}
      - IMAGE_ARG_JAVA_OPTS_USER_LANGUAGE=${IMAGE_ARG_JAVA_OPTS_USER_LANGUAGE:-zh}
      - IMAGE_ARG_JAVA_OPTS_USER_REGION=${IMAGE_ARG_JAVA_OPTS_USER_REGION:-CN}
    image: ${IMAGE_PREFIX:-cirepo}/java:${IMAGE_TAG:-oracle-9.0.4-jdk-alpine}
