version: '3.6'
services:
  java-oracle-8-jdk-alpine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
      - build_fileserver=${BUILD_FILESERVER:-}
    image: ${DOCKER_REGISTRY:-cirepo}/java:oracle-8u171-jdk-alpine
